export const CATEGORYPRODUCT = 'CATEGORYPRODUCT';
export const LISTPRODUCT = 'LISTPRODUCT';
export const FEATUREDPRODUCT = 'FEATUREDPRODUCT';
export const VIEWPRODUCT = 'VIEWPRODUCT';

export const CARTPRODUCT = 'CARTPRODUCT';
export const ORDERPRODUCT = 'ORDERPRODUCT';
